### PR TITLE
Add PHP 8.0 support and bump Laravel 8 version to 8.75

### PR DESCRIPTION
**Pull request by stephenjude**

### CODE REVIEW

**Comment by stephenjude** [comment]
@JonoB Please look into this PR. I am ready to add 8.1 support and Laravel 9 support too.

**Comment by JonoB** [comment]
It would be great if we could get some more input on this PR - particularly if there is anyone running it on PHP8

**Comment by stephenjude** [comment]
I am currently running it on 8.1.  I also built out the API SDK too but I haven’t published it. Still testing out on production to check the stability. You can take a look here. 

https://github.com/stephenjude/laravel-sendportal

**Comment by devhus** [comment]
Thanks for the hard work, How long this PR might take to be ready?

**Pull request closed without merging**
